name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - run: mkdir -p tests/__screenshots__ && echo yo > tests/__screenshots__/${{ matrix.os }}.txt
    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '14.x'
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test -u
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        ACTIONS_STEP_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "tests/__screenshots__"
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
